#!/usr/bin/env python
from math import hypot, pi, atan, fabs, sqrt
from Nature import Nature
from Wind import Wind

__author__ = 'dmytro'


class Turbine(Nature):
    """
    Wind turbine representation
    Contains necessary parameters as
    x-coordinate, y-coordinate, rotor diameter, height of the axis of rotation,
    Wind at x,y coordinate
    """

    def __init__(self, x, y, d, w=Wind(speed=0, direction=0), xi=0.4, h=10):
        """
        Initializing wind turbine parameters
        :param x: x-coordinate
        :param y: y-coordinate
        :param d: rotor diameter in [meters]
        :param h: height of the axis of rotation in [meters]
        :param v: wind speed at the point x,y in [meters per second]
        :return:
        """
        self.x = x
        self.y = y
        self.d = d
        self.h = h
        self.w = w
        self.xi = xi

    @property
    def area(self):
        """
        Area occupied by wind turbine's rotor
        :return double: swept area of rotor in [square meters]
        """
        return round(pi * self.d**2 / 4, 2)

    @property
    def power(self):
        """
        Power generated by turbine
        :return double: power at specified wind speed in [kWats]
        """
        return round(0.5 * self.xi * self.rho * self.area * self.w.v0**3, 2)

    def dist(self, turbine):
        """
        Distance to another wind turbine
        :param turbine: turbine to calculate distance to
        :return double: distance in meters
        """
        return round(hypot(self.x-turbine.x, self.y-turbine.y), 0)

    def direction(self, turbine):
        """
        Angle (the direction) to another wind turbine
        :param turbine: turbine to calculate direction to
        :return:angle in [radians]
        """
        if self.x == turbine.x:
            return pi/2
        if self.y == turbine.y:
            return float(0)

        return round(atan(abs(self.y-turbine.y) / abs(self.x-turbine.x)), 4)

    def set_wind(self, speed, direction):
        """
        Setting speed f wind at rotor point
        :return:
        """
        self.w.set_speed(speed)
        self.w.set_direction(direction)

    def __repr__(self):
        """
        String representation of turbine
        :return: string
        """
        return "Turbine: ({x:3.0f}, {y:3.0f}) ({v:2.0f}, {d:2.0f})"\
            .format(x=self.x, y=self.y, v=self.w.v0, d=self.w.direction)

    def __lt__(self, other):
        """
        Compare two turbines by their place from origin (0, 0)
        :param other: turbine to compare to
        :return: boolean
        """
        self_dist = sqrt(self.x**2 + self.y**2)
        other_dist = sqrt(other.x**2 + other.y**2)
        return self_dist < other_dist


if __name__ == "__main__":
    pass
